from flask.ext.sqlalchemy import SQLAlchemy
import datetime
db = SQLAlchemy()


class Document(db.Model):
    __tablename__ = 'Document'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(500), nullable=False)
    description = db.Column(db.String(500), nullable=False)
    datePublished = db.Column(db.Date, nullable=False)
    dateSubmitted = db.Column(db.DateTime, nullable=False)
    dateCreated = db.Column(db.DATE, nullable=False)
    filename = db.Column(db.String(255), nullable=False)
    common_id = db.Column(db.Integer, default=None)
    section_id = db.Column(db.Integer, default=None)
    status = db.Column(db.Enum('published', 'removed', 'publishing', 'not_approved'), nullable=False, default='publishing')
    approved = db.Column(db.Enum('yes', 'no'), default=False)
    reason = db.Column(db.String(255), default=None)
    hardcopy = db.Column(db.Enum('yes', 'no'), default=None)
    doc_url = db.Column(db.String(255), default=None)
    num_access = db.Column(db.Integer, default=0)
    agency = db.Column(db.Enum( 'Aging',
                            'Buildings',
                            'Campaign Finance',
                            'Children''s Services',
                            'City Council',
                            'City Clerk',
                            'City Planning',
                            'Citywide Admin Svcs',
                            'Civilian Complaint',
                            'Comm - Police Corr',
                            'Community Assistance',
                            'Comptroller',
                            'Conflicts of Interest',
                            'Consumer Affairs',
                            'Contracts',
                            'Correction',
                            'Criminal Justice Coordinator',
                            'Cultural Affairs',
                            'DOI - Investigation',
                            'Design/Construction',
                            'Disabilities',
                            'District Atty, NY County',
                            'Districting Commission',
                            'Domestic Violence',
                            'Economic Development',
                            'Education, Dept. of',
                            'Elections, Board of',
                            'Emergency Mgmt.',
                            'Employment',
                            'Empowerment Zone',
                            'Environmental - DEP',
                            'Environmental - OEC',
                            'Environmental - ECB',
                            'Equal Employment',
                            'Film/Theatre',
                            'Finance',
                            'Fire',
                            'FISA',
                            'Health and Mental Hyg.',
                            'HealthStat',
                            'Homeless Services',
                            'Hospitals - HHC',
                            'Housing - HPD',
                            'Human Rights',
                            'Human Rsrcs - HRA',
                            'Immigrant Affairs',
                            'Independent Budget',
                            'Info. Tech. and Telecom.',
                            'Intergovernmental',
                            'International Affairs',
                            'Judiciary Committee',
                            'Juvenile Justice',
                            'Labor Relations',
                            'Landmarks',
                            'Law Department',
                            'Library - Brooklyn',
                            'Library - New York',
                            'Library - Queens',
                            'Loft Board',
                            'Management and Budget',
                            'Mayor',
                            'Metropolitan Transportation Authority',
                            'NYCERS',
                            'Operations',
                            'Parks and Recreation',
                            'Payroll Administration',
                            'Police',
                            'Police Pension Fund',
                            'Probation',
                            'Public Advocate',
                            'Public Health',
                            'Public Housing-NYCHA',
                            'Records',
                            'Rent Guidelines',
                            'Sanitation',
                            'School Construction',
                            'Small Business Svcs',
                            'Sports Commission',
                            'Standards and Appeal',
                            'Tax Appeals Tribunal',
                            'Tax Commission',
                            'Taxi and Limousine',
                            'Transportation',
                            'Trials and Hearings',
                            'Veterans - Military',
                            'Volunteer Center',
                            'Voter Assistance',
                            'Youth & Community'), nullable=False)
    category = db.Column(db.Enum('Business and Consumers',
                             'Cultural/Entertainment',
                             'Education',
                             'Environment',
                             'Finance and Budget',
                             'Government Policy',
                             'Health',
                             'Housing and Buildings',
                             'Human Services',
                             'Labor Relations',
                             'Public Safety',
                             'Recreation/Parks',
                             'Sanitation',
                             'Technology',
                             'Transportation'), nullable=False)
    type = db.Column(db.Enum('Annual Report',
                         'Audit Report',
                         'Bond Offering - Official Statements',
                         'Budget Report',
                         'Consultant Report',
                         'Guide - Manual',
                         'Hearing - Minutes',
                         'Legislative Document',
                         'Memoranda - Directive',
                         'Press Release',
                         'Serial Publication',
                         'Staff Report',
                         'Report'), nullable=False)
    users = db.relationship('Submit')

class User(db.Model):
    __tablename__ = 'User'
    uid = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(255), nullable=False, unique=True)
    password = db.Column(db.String(128), nullable=False)
    first = db.Column(db.String(255), nullable=False)
    last = db.Column(db.String(255), nullable=False)
    agency = db.Column(db.Enum( 'Aging',
                            'Buildings',
                            'Campaign Finance',
                            'Children''s Services',
                            'City Council',
                            'City Clerk',
                            'City Planning',
                            'Citywide Admin Svcs',
                            'Civilian Complaint',
                            'Comm - Police Corr',
                            'Community Assistance',
                            'Comptroller',
                            'Conflicts of Interest',
                            'Consumer Affairs',
                            'Contracts',
                            'Correction',
                            'Criminal Justice Coordinator',
                            'Cultural Affairs',
                            'DOI - Investigation',
                            'Design/Construction',
                            'Disabilities',
                            'District Atty, NY County',
                            'Districting Commission',
                            'Domestic Violence',
                            'Economic Development',
                            'Education, Dept. of',
                            'Elections, Board of',
                            'Emergency Mgmt.',
                            'Employment',
                            'Empowerment Zone',
                            'Environmental - DEP',
                            'Environmental - OEC',
                            'Environmental - ECB',
                            'Equal Employment',
                            'Film/Theatre',
                            'Finance',
                            'Fire',
                            'FISA',
                            'Health and Mental Hyg.',
                            'HealthStat',
                            'Homeless Services',
                            'Hospitals - HHC',
                            'Housing - HPD',
                            'Human Rights',
                            'Human Rsrcs - HRA',
                            'Immigrant Affairs',
                            'Independent Budget',
                            'Info. Tech. and Telecom.',
                            'Intergovernmental',
                            'International Affairs',
                            'Judiciary Committee',
                            'Juvenile Justice',
                            'Labor Relations',
                            'Landmarks',
                            'Law Department',
                            'Library - Brooklyn',
                            'Library - New York',
                            'Library - Queens',
                            'Loft Board',
                            'Management and Budget',
                            'Mayor',
                            'Metropolitan Transportation Authority',
                            'NYCERS',
                            'Operations',
                            'Parks and Recreation',
                            'Payroll Administration',
                            'Police',
                            'Police Pension Fund',
                            'Probation',
                            'Public Advocate',
                            'Public Health',
                            'Public Housing-NYCHA',
                            'Records',
                            'Rent Guidelines',
                            'Sanitation',
                            'School Construction',
                            'Small Business Svcs',
                            'Sports Commission',
                            'Standards and Appeal',
                            'Tax Appeals Tribunal',
                            'Tax Commission',
                            'Taxi and Limousine',
                            'Transportation',
                            'Trials and Hearings',
                            'Veterans - Military',
                            'Volunteer Center',
                            'Voter Assistance',
                            'Youth & Community'), nullable=False)
    email = db.Column(db.String(255), nullable=False, unique=True)
    date_joined = db.Column(db.DateTime)
    last_visited = db.Column(db.Date)
    visits = db.Column(db.Integer, default=0)
    documents = db.relationship('Submit')

class Submit(db.Model):
    __tablename__ = 'Submit'
    uid = db.Column(db.Integer, db.ForeignKey('User.uid'), primary_key=True)
    did = db.Column(db.Integer, db.ForeignKey('Document.id'), primary_key=True)